defaults:
  - base_evc_xlsr_yin

perturb_inputs: False

style_encoder:
  emotion_emb_dim: 256

  emotion_encoder:
    out_dim: 1024

  speaker_encoder:
    in_dim: 80
    hidden_dim: 256
    out_dim: 256

content_encoder:
  out_dim: 1024

pitch_encoder:
  sample_rate: 16000
  hop_length: 320  # same as mel_transform.hop_length
  win_length: 1480
  tau_max: 1480  # produces 80 midi values
  out_dim: 80

decoder:
  frame_wise_pitch: True
  in_dim: 128
  hidden_dim: 128
  out_dim: 80
  kernel_size: 5
  dilation_rate: 1
  n_layers: 8
  gin_channels: 512

diffusion:
  in_dim: 80
  dec_dim: 128
  cond_dim: 128
  use_ref_t: False
  beta_min: 0.05
  beta_max: 20.0
  gin_channels: 512

vocoder:
  in_dim: 80
  resblock: 1
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  upsample_rates: [5,4,4,2,2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [11,8,8,4,4]
