defaults:
  - base_vc_xlsr

style_encoder:
  in_dim: 80
  hidden_dim: 256
  out_dim: 256

content_encoder:
  out_dim: 392

pitch_encoder:
  sample_rate: 16000

  f0_encoder:
    in_dim: 1
    out_dim: 128
    hidden_dim: 32
    levels: 1
    downs_t: [4]
    strides_t: [2]
    resnet1d:
      depth: 4
      m_conv: 1.0
      dilation_growth_rate: 3

  vq:
    k_bins: 20
    emb_dim: 128
    levels: 1
    mu: 0.99

  out_dim: 20

decoder:
  in_dim: 128
  hidden_dim: 128
  out_dim: 80
  kernel_size: 5
  dilation_rate: 1
  n_layers: 8
  gin_channels: 256

diffusion:
  in_dim: 80
  dec_dim: 128
  cond_dim: 128
  use_ref_t: False
  beta_min: 0.05
  beta_max: 20.0
  gin_channels: 256

vocoder:
  in_dim: 80
  resblock: 1
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  upsample_rates: [5,4,4,2,2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [11,8,8,4,4]
