repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest version
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest version
    hooks:
      - id: flake8
        args: [
          "--max-line-length=88",
          "--ignore=E203,W503",
        ]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0  # Use the latest version
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0  # Use the latest version
    hooks:
      - id: mypy
        args: [
          --implicit-optional,
          --show-error-codes,
          --ignore-missing-imports,
        ]
