seed: 42
batch_size: 32
epochs: 10
segment_size: 38000
learning_rate: 5e-5
lr_decay: 0.999875
betas: [0.8, 0.99]
eps: 1e-9
use_fp16_scaling: false  # gradient scaling
diff_loss_coef: 1.0
rec_loss_coef: 1.0
log_interval: 500
eval_interval: 10000
save_interval: 10000
tensorboard_dir: ${hydra:runtime.cwd}/${hydra:run.dir}/tensorboard
eval_n_batches: 100  # Number of batches to eval during training
