training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  segment_size: 35840

models:
  src_ftr_encoder:
    speaker_encoder:
      in_dim: 80
      hidden_dim: 256
      out_dim: 256

    pitch_encoder:
      f0_encoder:
        in_dim: 1
        out_dim: 128
        hidden_dim: 32
        levels: 1
        downs_t: [4]
        strides_t: [2]
        resnet1d:
          depth: 4
          m_conv: 1.0
          dilation_growth_rate: 3

      vq:
        k_bins: 20
        emb_dim: 128
        levels: 1
        mu: 0.99

    decoder:
      in_dim: 128
      hidden_dim: 128
      kernel_size: 5
      dilation_rate: 1
      n_layers: 8
      n_mel_channels: 80
      gin_channels: 256

  src_ftr_decoder:
    dec_dim: 128
    spk_dim: 128
    use_ref_t: False
    beta_min: 0.05
    beta_max: 20.0

  vocoder:
    in_dim: 80
    resblock: 1
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
    upsample_rates: [5,4,4,2,2]
    upsample_initial_channel: 512
    upsample_kernel_sizes: [11,8,8,4,4]

data:
  dataset:
    name: "MSP-Podcast"
    path: "/home/alex/dev/DDDM-EVC/datasets/msp-podcast/"
    sampling_rate: 16000
    segment_size: 35840
    segment_seed: 10

  dataloader:
    num_workers: 4
    distributed: False
    pin_memory: True
    drop_last: False

  mel_transform:
    sample_rate: 16000
    filter_length: 1280
    win_length: 1280
    hop_length: 320
    n_mel_channels: 80
    f_min: 0
    f_max: 8000
